# Site settings
title: Marc Grenier | Android developer
baseurl: https://marcgrenier.github.io/
url: https://marcgrenier.github.io/

permalink: /404.html

# Author settings
author:
  name: Marc Grenier

# Projects settings
projects:
  - project1:
    name: Code Name
    description: Android table game
    content: '<div class="image blue"><i class="fa fa-user-secret"></i></div>'
    permalink: "/project/codename/"
  - project2:
    name: Rantalk
    description: Talk to random people
    content: <div class="image green"><i class="fa fa-comments"></i></div>
    permalink: /project/rantalk
  - project3:
    name: Picmodifier
    description: Photo editor
    content: <div class="image amber"><i class="fa fa-camera-retro"></i></div>
    permalink: /project/picmodifier/
  - project4:
    name: Minesweeper
    description: Javascript game
    content: <div class="image orange"><i class="fa fa-gamepad"></i></div>
    permalink: /project/minesweeper
  - project5:
    name: Asteroïd
    description: Android Survival Game
    content: <div class="image black"><img src="/assets/images/asteroid1.png" alt="Asteroid icon"/></div>
    permalink: /project/asteroid/
  - project6:
    name: AreaB51
    description: Multiplayer third-person shooter
    content: <div class="image red"><img src="/assets/images/areab51.gif" alt="areaB51 character"/></div>
    permalink: /project/areab51/
